// PHCA v3.0 — Shared Data Types (Rust)
// Corresponds to python/phca/config.py

use serde::{Deserialize, Serialize};

/// Resource bound vector ρ for a module.
/// Matches v3.0 §2.1 Definition 2.1.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceBounds {
    pub b_time: f64,        // max runtime per cycle (seconds)
    pub b_mem: f64,         // max memory (bytes)
    pub b_energy: f64,      // max energy (Joules, estimated from FLOPs)
    pub entropy_floor: f64, // minimum acceptable H(beliefs)
}

impl ResourceBounds {
    pub fn new(b_time: f64, b_mem: f64, b_energy: f64, entropy_floor: f64) -> Self {
        Self { b_time, b_mem, b_energy, entropy_floor }
    }
}

/// Canonical state representation flowing through the system.
/// Matches v3.0 Blueprint Appendix D.1.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StateVector {
    pub values: Vec<f64>,       // float64 array of dimension d
    pub precision: Vec<f64>,    // per-element precision p_i (same dimension)
    pub timestamp: f64,         // monotonic cycle counter
    pub grounding_level: u8,    // 0, 1, or 2 (from ASI)
}

impl StateVector {
    pub fn new(values: Vec<f64>, precision: Vec<f64>, timestamp: f64, grounding_level: u8) -> Self {
        assert_eq!(values.len(), precision.len());
        Self { values, precision, timestamp, grounding_level }
    }

    pub fn dim(&self) -> usize {
        self.values.len()
    }
}

/// Goal representation generated by MDIM.
/// Matches v3.0 Blueprint Appendix D.1.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalVector {
    pub drive_id: u8,               // D1–D6 (0–5)
    pub target_values: Vec<f64>,     // desired state (may be partial)
    pub tolerance: f64,             // acceptable deviation
    pub creation_cycle: u64,        // when this goal was created
    pub priority: f64,              // from softmax weight
}

impl GoalVector {
    pub fn new(drive_id: u8, target_values: Vec<f64>, tolerance: f64, creation_cycle: u64, priority: f64) -> Self {
        Self { drive_id, target_values, tolerance, creation_cycle, priority }
    }
}

// ── FFI stubs for Python interop (via PyO3) ──────────────────

/// Placeholder: will be extended with maturin bindings.
/// For now, types are serialized via JSON across the FFI boundary.
#[cfg(feature = "pyo3")]
mod python_bindings {
    use pyo3::prelude::*;
    use super::*;

    #[pyclass(name = "ResourceBounds")]
    pub struct PyResourceBounds {
        inner: ResourceBounds,
    }

    #[pymethods]
    impl PyResourceBounds {
        #[new]
        pub fn new(b_time: f64, b_mem: f64, b_energy: f64, entropy_floor: f64) -> Self {
            Self { inner: ResourceBounds::new(b_time, b_mem, b_energy, entropy_floor) }
        }

        pub fn to_json(&self) -> String {
            serde_json::to_string(&self.inner).unwrap()
        }
    }
}

// ── Tests ───────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_resource_bounds_creation() {
        let rb = ResourceBounds::new(0.5, 1_000_000.0, 100.0, 0.01);
        assert_eq!(rb.b_time, 0.5);
        assert!(rb.b_mem > 0.0);
    }

    #[test]
    fn test_state_vector_creation() {
        let sv = StateVector::new(
            vec![0.1, 0.2, 0.3],
            vec![1.0, 0.8, 0.5],
            42.0,
            1,
        );
        assert_eq!(sv.dim(), 3);
        assert_eq!(sv.grounding_level, 1);
    }

    #[test]
    fn test_goal_vector_creation() {
        let gv = GoalVector::new(1, vec![0.5, 0.5], 0.1, 0, 0.8);
        assert_eq!(gv.drive_id, 1);
        assert_eq!(gv.target_values.len(), 2);
    }

    #[test]
    fn test_serialization_roundtrip() {
        let rb = ResourceBounds::new(0.5, 1_000_000.0, 100.0, 0.01);
        let json = serde_json::to_string(&rb).unwrap();
        let rb2: ResourceBounds = serde_json::from_str(&json).unwrap();
        assert_eq!(rb.b_time, rb2.b_time);
    }
}
