"""
PHCA v3.0 — Shared Configuration & Data Types.

Implements the core data types from Blueprint Appendix D.1.
These types flow through every module in the cognitive cycle.

Cross-ref: v3.0 Blueprint §B, Appendix D.1
"""

from __future__ import annotations

import numpy as np
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any


class ASIStatus(Enum):
    """ASI sanitization result status."""
    OK = auto()
    SENSOR_FAILURE = auto()


class StreamID(Enum):
    """TSPL stream identifiers (v3.0 §3.1)."""
    P_STREAM = "procedural"
    E_STREAM = "episodic"
    S_STREAM = "semantic"


class DriveID(Enum):
    """MDIM drive identifiers (v3.0 §3.3)."""
    D1 = "prediction_error"
    D2 = "criticality"
    D3 = "competence"
    D4 = "epistemic_curiosity"
    D5 = "energy_efficiency"
    D6 = "empowerment"


# ── Core Data Types ───────────────────────────────────────────


@dataclass
class StateVector:
    """
    Canonical state representation flowing through the system.

    Attributes:
        values: float32 array of dimension d
        precision: per-element precision p_i (same dimension as values)
        timestamp: monotonic cycle counter
        grounding_level: 0 (raw), 1 (feature), or 2 (semantic) — from ASI
    """
    values: np.ndarray
    precision: np.ndarray
    timestamp: float = 0.0
    grounding_level: int = 1  # default to feature-level

    def __post_init__(self):
        assert self.values.shape == self.precision.shape, \
            f"values shape {self.values.shape} != precision shape {self.precision.shape}"
        assert self.grounding_level in (0, 1, 2), \
            f"grounding_level must be 0, 1, or 2, got {self.grounding_level}"

    @property
    def dim(self) -> int:
        return self.values.shape[0]

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dict (numpy arrays → lists)."""
        return {
            "values": self.values.tolist(),
            "precision": self.precision.tolist(),
            "timestamp": self.timestamp,
            "grounding_level": self.grounding_level,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> StateVector:
        """Deserialize from a dict."""
        return cls(
            values=np.array(data["values"], dtype=np.float32),
            precision=np.array(data["precision"], dtype=np.float32),
            timestamp=data["timestamp"],
            grounding_level=data["grounding_level"],
        )

    def to_bytes(self) -> bytes:
        """Serialize to bytes for SQLite BLOB storage."""
        try:
            import orjson
            return orjson.dumps(self.to_dict())
        except ImportError:
            import json
            return json.dumps(self.to_dict()).encode()

    @classmethod
    def from_bytes(cls, data: bytes) -> StateVector:
        """Deserialize from bytes (SQLite BLOB)."""
        try:
            import orjson
            return cls.from_dict(orjson.loads(data))
        except ImportError:
            import json
            return cls.from_dict(json.loads(data.decode()))


@dataclass
class ResourceBounds:
    """
    Resource bound vector ρ for a module (v3.0 §2.1 Definition 2.1).

    Attributes:
        B_time: max runtime per cycle (seconds)
        B_mem: max memory (bytes)
        B_energy: max energy (Joules, estimated from FLOPs)
        entropy_floor: minimum acceptable H(beliefs) — A3 enforcement
    """
    B_time: float
    B_mem: float
    B_energy: float
    entropy_floor: float = 0.01  # default ε > 0 per A3

    def __post_init__(self):
        assert self.B_time > 0, "B_time must be positive"
        assert self.B_mem > 0, "B_mem must be positive"
        assert self.entropy_floor >= 0, "entropy_floor must be non-negative"


@dataclass
class GoalVector:
    """
    Goal representation generated by MDIM (v3.0 §3.3).

    Attributes:
        drive_id: D1–D6 (0–5)
        target_state: desired state (may be partial)
        tolerance: acceptable deviation from target
        creation_cycle: when this goal was created
        priority: from softmax weight
    """
    drive_id: int
    target_state: StateVector | None = None
    tolerance: float = 0.1
    creation_cycle: int = 0
    priority: float = 0.0

    @property
    def drive_name(self) -> str:
        try:
            return DriveID(f"D{self.drive_id}").value
        except ValueError:
            return f"unknown_drive_{self.drive_id}"


@dataclass
class ConstraintViolation:
    """
    A constraint violation detected by the RBTA enforcer.

    Attributes:
        module_id: which module violated its bound
        bound_type: which resource bound was violated
        measured: the measured value
        allowed: the maximum allowed value
    """
    module_id: str
    bound_type: str  # "TIME", "MEM", "ENERGY", "ENTROPY", "SENSOR"
    measured: float
    allowed: float


# ── Default Configurations ────────────────────────────────────

DEFAULT_MODULE_BOUNDS: dict[str, ResourceBounds] = {
    "ASI": ResourceBounds(B_time=0.002, B_mem=100_000, B_energy=10.0),
    "WM": ResourceBounds(B_time=0.005, B_mem=50_000, B_energy=5.0),
    "G'": ResourceBounds(B_time=0.020, B_mem=500_000, B_energy=50.0),
    "PE": ResourceBounds(B_time=0.025, B_mem=200_000, B_energy=20.0),
    "PEU": ResourceBounds(B_time=0.001, B_mem=10_000, B_energy=1.0),
    "TSPL-P": ResourceBounds(B_time=0.020, B_mem=300_000, B_energy=30.0),
    "TSPL-E": ResourceBounds(B_time=0.020, B_mem=400_000, B_energy=30.0),
    "TSPL-S": ResourceBounds(B_time=0.020, B_mem=400_000, B_energy=30.0),
    "MDIM": ResourceBounds(B_time=0.200, B_mem=100_000, B_energy=10.0),
    "CR": ResourceBounds(B_time=0.005, B_mem=50_000, B_energy=5.0),
    "ATTN": ResourceBounds(B_time=0.002, B_mem=20_000, B_energy=2.0),
    "HPM": ResourceBounds(B_time=0.002, B_mem=50_000, B_energy=5.0),
    "CONSOL": ResourceBounds(B_time=0.001, B_mem=10_000, B_energy=1.0),
}

# Cycle timing constants (seconds)
CYCLE_TARGET = 0.500       # 500ms target
T_COMP = 0.001             # 1ms composition overhead
T_SYNC = 0.002             # 2ms synchronization overhead
