"""
PHCA v3.0 — Shared Configuration & Data Types.

Implements the core data types from Blueprint Appendix D.1.
These types flow through every module in the cognitive cycle.

Cross-ref: v3.0 Blueprint §B, Appendix D.1
"""

from __future__ import annotations

import numpy as np
from dataclasses import dataclass
from enum import Enum, auto
from typing import Optional, Union


# ── Action Space Types (Phase 6 — continuous-action unlock) ────


@dataclass(frozen=True)
class DiscreteSpace:
    """Discrete action space with `n` mutually-exclusive actions."""

    n: int


@dataclass(frozen=True)
class ContinuousSpace:
    """Continuous action space: a real vector in [low, high]^dim.

    `low`/`high` are broadcastable to shape (dim,). Used by the MPC-style
    continuous action selector (Phase 6 / A2) to sample candidate actions.
    """

    low: np.ndarray
    high: np.ndarray
    dim: int


ActionSpace = Union[DiscreteSpace, ContinuousSpace]


def discrete_space(n: int) -> DiscreteSpace:
    return DiscreteSpace(n=n)


def continuous_space(low, high, dim: int) -> ContinuousSpace:
    return ContinuousSpace(
        low=np.broadcast_to(np.asarray(low, dtype=np.float32), (dim,)).copy(),
        high=np.broadcast_to(np.asarray(high, dtype=np.float32), (dim,)).copy(),
        dim=dim,
    )


class ASIStatus(Enum):
    """ASI sanitization result status."""
    OK = auto()
    PARTIAL_FAILURE = auto()
    SENSOR_FAILURE = auto()


class StreamID(Enum):
    """TSPL stream identifiers (v3.0 §3.1)."""
    P_STREAM = "procedural"


class DriveID(Enum):
    """MDIM drive identifiers (v3.0 §3.3)."""
    D1 = "prediction_error"
    D2 = "criticality"
    D3 = "competence"
    D4 = "epistemic_curiosity"
    D5 = "energy_efficiency"
    D6 = "empowerment"


# ── Core Data Types ───────────────────────────────────────────


@dataclass
class StateVector:
    """
    Canonical state representation flowing through the system.

    Attributes:
        values: float32 array of dimension d
        precision: per-element precision p_i (same dimension as values)
        timestamp: monotonic cycle counter
        grounding_level: 0 (raw), 1 (feature), 2 (semantic — Phase 3.2+)
    """
    values: np.ndarray
    precision: np.ndarray
    timestamp: float = 0.0
    grounding_level: int = 1

    def __post_init__(self):
        assert self.values.shape == self.precision.shape, \
            f"values shape {self.values.shape} != precision shape {self.precision.shape}"

    @property
    def dim(self) -> int:
        return self.values.shape[0]

    def to_bytes(self) -> bytes:
        """Serialize state vector to bytes for SQLite BLOB storage (M3 dependency)."""
        data = {
            "values": self.values.tolist(),
            "precision": self.precision.tolist(),
            "timestamp": self.timestamp,
        }
        try:
            import orjson
            return orjson.dumps(data)
        except ImportError:
            import json
            return json.dumps(data).encode()

    @classmethod
    def from_bytes(cls, data: bytes) -> StateVector:
        """Deserialize state vector from bytes (M3 dependency)."""
        try:
            import orjson
            parsed = orjson.loads(data)
        except ImportError:
            import json
            parsed = json.loads(data.decode())
        # remove grounding_level if present (legacy serialization) — G-018
        parsed.pop("grounding_level", None)
        return cls(
            values=np.array(parsed["values"], dtype=np.float32),
            precision=np.array(parsed["precision"], dtype=np.float32),
            timestamp=parsed["timestamp"],
        )




@dataclass
class ResourceBounds:
    """
    Resource bound vector ρ for a module (v3.0 §2.1 Definition 2.1).

    Attributes:
        B_time: max runtime per cycle (seconds)
        B_mem: max memory (bytes)
        B_energy: max energy (Joules, estimated from FLOPs)
        entropy_floor: minimum acceptable H(beliefs) — A3 enforcement
    """
    B_time: float
    B_mem: float
    B_energy: float
    entropy_floor: float = 0.01  # default ε > 0 per A3

    def __post_init__(self):
        assert self.B_time > 0, "B_time must be positive"
        assert self.B_mem > 0, "B_mem must be positive"
        assert self.B_energy > 0, "B_energy must be positive"
        assert self.entropy_floor >= 0, "entropy_floor must be non-negative"


@dataclass
class GoalVector:
    """
    Goal representation generated by MDIM (v3.0 §3.3).

    Attributes:
        drive_id: D1–D6 (0–5)
        target_state: desired state (may be partial)
        tolerance: acceptable deviation from target
        creation_cycle: when this goal was created
        priority: from softmax weight
    """
    drive_id: int
    target_state: StateVector | None = None
    tolerance: float = 0.1
    creation_cycle: int = 0
    priority: float = 0.0

    @property
    def drive_name(self) -> str:
        try:
            return DriveID(f"D{self.drive_id}").value
        except ValueError:
            return f"unknown_drive_{self.drive_id}"


@dataclass
class ConstraintViolation:
    """
    A constraint violation detected by the RBTA enforcer.

    Attributes:
        module_id: which module violated its bound
        bound_type: which resource bound was violated
        measured: the measured value
        allowed: the maximum allowed value
        severity: violation magnitude (0-1); 0=barely over, 1=far over
    """
    module_id: str
    bound_type: str  # "TIME", "MEM", "ENERGY", "ENTROPY", "SENSOR"
    measured: float
    allowed: float
    severity: float = 0.5

    def __post_init__(self):
        # Severity = normalised absolute deviation from bound, direction-agnostic.
        # Works for both "over" (TIME/MEM/ENERGY/SENSOR: measured > allowed) and
        # "under" (ENTROPY: measured < allowed) violations.
        if self.allowed > 0:
            ratio = abs(self.measured - self.allowed) / max(self.allowed, 1e-9)
            self.severity = float(np.clip(ratio / 5.0, 0.0, 1.0))
        else:
            self.severity = 0.0


# ── Default Configurations ────────────────────────────────────

DEFAULT_MODULE_BOUNDS: dict[str, ResourceBounds] = {
    "ASI": ResourceBounds(B_time=0.010, B_mem=100_000, B_energy=10.0),
    "WM": ResourceBounds(B_time=0.010, B_mem=50_000, B_energy=5.0),
    "G'": ResourceBounds(B_time=0.040, B_mem=1000_000, B_energy=50.0),
    "PE": ResourceBounds(B_time=0.300, B_mem=200_000, B_energy=20.0),
    "PEU": ResourceBounds(B_time=0.010, B_mem=10_000, B_energy=1.0),
    "TSPL-P": ResourceBounds(B_time=0.030, B_mem=300_000, B_energy=30.0),
    "MDIM": ResourceBounds(B_time=0.200, B_mem=100_000, B_energy=10.0),
    "CR": ResourceBounds(B_time=0.010, B_mem=50_000, B_energy=5.0),
    "ATTN": ResourceBounds(B_time=0.005, B_mem=20_000, B_energy=2.0),
    "HPM": ResourceBounds(B_time=0.005, B_mem=50_000, B_energy=5.0),
    "CONSOL": ResourceBounds(B_time=0.050, B_mem=10_000, B_energy=1.0),
    "ACTION": ResourceBounds(B_time=0.030, B_mem=10_000, B_energy=10.0),
}

# Cycle timing constants (seconds)
CYCLE_TARGET = 0.500       # 500ms target
T_COMP = 0.001             # 1ms composition overhead
T_SYNC = 0.002             # 2ms synchronization overhead

# PER (Prioritized Experience Replay) constants
PER_ALPHA = 0.6            # prioritization exponent (0=uniform, 1=full priority)
PER_BETA_INIT = 0.4        # initial importance-sampling correction
PER_BETA_FINAL = 1.0       # final IS correction (fully unbiased)
PER_BETA_ANNEAL_STEPS = 100_000  # cycles to anneal beta from init to final
PER_EPSILON = 0.01         # floor for priority (keeps stale episodes sampleable)

# Φ (Criticality) constants
PHI_TARGET = 1.0           # target criticality setpoint (||dL/dx|| / sqrt(d) ~ 1.0)
PHI_MAX = 10.0             # maximum phi clip (safety bound)

# Async cycle (Feature 1) constants
STALE_THRESHOLD_MS = 100   # max age (ms) before a PerceptionFrame is considered stale


@dataclass
class PerceptionFrame:
    """A perception-action observation frame for the async cycle.

    Captures the observation received and the action taken at a given
    environment step, along with timing metadata for staleness detection.
    """
    observation: np.ndarray
    action: int | None
    timestamp: float
    age: int = 0


@dataclass
class ActionResult:
    """Result of executing an action in the environment.

    Attributes:
        reward: Reward received.
        terminal: Whether the episode terminated.
        state: New observation after step.
        age: Cycle-age of the associated PerceptionFrame when executed.
        action: The action taken (int for discrete, ndarray for continuous).
        info: Info dict from env.step (goal_reached, agent_pos, etc.).
    """
    reward: float
    terminal: bool
    state: np.ndarray
    age: int = 0
    action: int | np.ndarray | None = None
    info: dict | None = None
