"""
PHCA v3.0 — MDIM (Multi-Drive Intrinsic Motivation).

Phase 3.2: Full Pareto front with D1-D5 active drives (D6 deferred) and
meta-stable state selection. Generates goals weighted by drive deficit.

v3.0 Reference: §3.3 Definition 3.5, §3.3 Definition 3.6,
v3.0 Patch §2.4 (Pareto front + meta-stable state)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from phca.config import DriveID, GoalVector, StateVector


@dataclass
class DriveState:
    """Current state of a single drive.

    Attributes:
        drive_id: D1-D6 identifier.
        value: Current drive magnitude (higher = more urgent).
        deficit: Distance from target/setpoint (0 = satisfied).
        target: Desired setpoint value.
        goal: Current goal generated by this drive.
    """
    drive_id: int
    value: float = 0.0
    deficit: float = 0.0
    target: float = 0.0
    goal: Optional[GoalVector] = None


@dataclass
class GoalStackEntry:
    """A single entry in the MDIM goal stack.

    Attributes:
        goal: The goal vector.
        sub_goals: List of decomposed sub-goals.
        depth: Decomposition depth (0 = root).
        completed: Whether this goal has been completed.
    """
    goal: GoalVector
    sub_goals: List[GoalVector] = field(default_factory=list)
    depth: int = 0
    completed: bool = False


@dataclass
class MetaStableState:
    """Meta-stable system state with all drives satisfied.

    Attributes:
        is_meta_stable: Whether all drives are within tolerance.
        drive_values: Snapshot of D1-D5 values at meta-stability.
        cycles_since_entry: How many cycles in meta-stable state.
    """
    is_meta_stable: bool = False
    drive_values: List[float] = field(default_factory=list)
    cycles_since_entry: int = 0


class MDIM:
    """Multi-Drive Intrinsic Motivation — Phase 3.2 full implementation.

    Phase 3.2 active drives:
        D1 — Prediction Error Minimization
        D2 — Complexity Seeking (Criticality)
        D3 — Competence Acquisition
        D4 — Epistemic Curiosity
        D5 — Energy Efficiency
        D6 — Empowerment (deferred to Phase 3.3)

    Mechanism:
        1. Each cycle, compute drive values from system context
        2. Compute deficits relative to targets
        3. Weight drives by softmax deficit
        4. Select winning drive and generate concrete goal
        5. Compute D1/D3/D5 Pareto front for meta-stable state

    v3.0 Reference: §3.3 Definition 3.6, v3.0 Patch §2.4
    """

    def __init__(self, state_dim: int = 4):
        """Initialize MDIM with default drive parameters.

        Args:
            state_dim: Dimensionality of state vectors used in goals.
        """
        self.state_dim = state_dim
        self._cycle = 0

        # Drive targets (setpoints)
        self._targets: Dict[int, float] = {
            1: 0.1,   # D1: low prediction error
            2: 0.5,   # D2: criticality setpoint (edge of chaos)
            3: 0.05,  # D3: low competence deficit (high accuracy)
            4: 0.3,   # D4: moderate uncertainty (curiosity sweet spot)
            5: 0.2,   # D5: low energy cost
            6: 0.5,   # D6: moderate empowerment (deferred)
        }

        # Drive states (updated each cycle)
        self.drives: Dict[int, DriveState] = {
            d: DriveState(drive_id=d) for d in range(1, 7)
        }

        # Goal stack
        self.goal_stack: List[GoalStackEntry] = []
        self._max_stack_depth: int = 5

        # Meta-stable state
        self.meta_stable: MetaStableState = MetaStableState()
        self._meta_stable_threshold: float = 0.15  # all deficits < threshold
        self._meta_stable_min_cycles: int = 3

        # CR-controlled temperature (set externally by CognitiveCycle)
        self.temperature: float = 1.0

        # Last generated goal
        self.current_goal: Optional[GoalVector] = None

        # History for debugging/monitoring
        self._drive_history: List[Dict[int, float]] = []
        self._goal_history: List[GoalVector] = []

    # ── Drive Computation ─────────────────────────────────────

    def compute_drives(self, context: Dict[str, Any]) -> Dict[int, DriveState]:
        """Compute all drive values from current system context.

        Args:
            context: Dict with keys:
                - prediction_error: float (for D1)
                - phi_criticality: float (for D2, approx -H(module_states))
                - skill_accuracy: float (for D3, 0.0-1.0)
                - model_entropy: float (for D4, G' posterior entropy)
                - energy_cost: float (for D5, computational cost / budget)
                - empowerment: float (for D6, deferred — always 0.5)

        Returns:
            Dict mapping drive_id → DriveState with computed values.
        """
        self._cycle += 1

        # Extract context with defaults
        prediction_error = context.get("prediction_error", 0.0)
        phi_criticality = context.get("phi_criticality", 0.5)
        skill_accuracy = context.get("skill_accuracy", 0.0)
        model_entropy = context.get("model_entropy", 0.5)
        energy_cost = context.get("energy_cost", 0.0)

        # D1: Prediction Error Minimization
        # Drive = current prediction error. Deficit = |error - target|
        d1_value = min(prediction_error, 10.0)
        d1_deficit = max(0.0, d1_value - self._targets[1])
        self.drives[1] = DriveState(
            drive_id=1, value=d1_value,
            deficit=d1_deficit, target=self._targets[1],
        )

        # D2: Complexity Seeking (Criticality)
        # Drive = |phi_current - phi_critical|. Maximize near critical point.
        d2_value = abs(phi_criticality - self._targets[2])
        d2_deficit = d2_value  # deficit = distance from setpoint
        self.drives[2] = DriveState(
            drive_id=2, value=d2_value,
            deficit=d2_deficit, target=self._targets[2],
        )

        # D3: Competence Acquisition
        # Drive = 1 - accuracy. Low accuracy → high drive.
        d3_value = max(0.0, 1.0 - skill_accuracy)
        d3_deficit = max(0.0, d3_value - self._targets[3])
        self.drives[3] = DriveState(
            drive_id=3, value=d3_value,
            deficit=d3_deficit, target=self._targets[3],
        )

        # D4: Epistemic Curiosity
        # Drive = model_entropy. Moderate entropy → exploration sweet spot.
        # Deficit = |entropy - target| — too much or too little drives curiosity
        d4_value = model_entropy
        d4_deficit = max(0.0, abs(d4_value - self._targets[4]))
        self.drives[4] = DriveState(
            drive_id=4, value=d4_value,
            deficit=d4_deficit, target=self._targets[4],
        )

        # D5: Energy Efficiency
        # Drive = energy_cost / budget. High cost → drive to optimize.
        d5_value = min(energy_cost, 1.0)
        d5_deficit = max(0.0, d5_value - self._targets[5])
        self.drives[5] = DriveState(
            drive_id=5, value=d5_value,
            deficit=d5_deficit, target=self._targets[5],
        )

        # D6: Empowerment
        # Measure action-effect channel capacity: I(state_t+1; a_t | state_t)
        # Approximated as entropy of state transitions under different actions.
        # High empowerment = many distinct outcomes from different actions.
        empowerment = context.get("empowerment", 0.3)
        # Also blend in prediction_error as a proxy for action effectiveness
        empowerment_blend = 0.7 * empowerment + 0.3 * min(prediction_error * 0.5, 1.0)
        d6_deficit = max(0.0, abs(empowerment_blend - self._targets[6]))
        self.drives[6] = DriveState(
            drive_id=6, value=empowerment_blend,
            deficit=d6_deficit, target=self._targets[6],
        )

        # Log drive history
        self._drive_history.append({
            d: self.drives[d].deficit for d in self.drives
        })
        if len(self._drive_history) > 1000:
            self._drive_history = self._drive_history[-500:]

        return dict(self.drives)

    # ── Pareto Front ──────────────────────────────────────────

    def compute_pareto_front(
        self, deficits: Optional[Dict[int, float]] = None,
    ) -> List[int]:
        """Compute Pareto-optimal drives given current deficits.

        Pareto front over D1 (prediction error), D3 (competence),
        and D5 (energy). A drive is Pareto-optimal if no other drive
        has both a higher deficit and higher priority.

        Phase 3.2: Simple Pareto front for D1/D3/D5.
        Phase 3.3: Full n-dimensional Pareto with D2/D4/D6.

        Args:
            deficits: Optional override of drive deficits.
                If None, uses self.drives current values.

        Returns:
            List of drive IDs that are on the Pareto front.
        """
        if deficits is None:
            deficits = {d: self.drives[d].deficit for d in [1, 3, 5]}

        pareto_ids: List[int] = []
        drive_ids = sorted(deficits.keys())

        for i in drive_ids:
            i_deficit = deficits.get(i, 0.0)
            dominated = False
            for j in drive_ids:
                if i == j:
                    continue
                j_deficit = deficits.get(j, 0.0)
                # j dominates i if j has higher deficit and higher priority
                # (priority is implicit in deficit magnitude for now)
                if j_deficit > i_deficit + 0.01:  # tolerance to avoid noise
                    dominated = True
                    break
            if not dominated:
                pareto_ids.append(i)

        return pareto_ids

    # ── Goal Generation ───────────────────────────────────────

    def generate_goal(self, context: Any = None) -> GoalVector:
        """Generate a goal based on current drive deficits.

        Phase 3.2:
        1. Compute drives from context (if string or None, use as simple call)
        2. Weight drives by softmax deficit
        3. Select winning drive (highest weighted deficit)
        4. Generate concrete goal from winning drive
        5. Update Pareto front and meta-stable state

        Args:
            context: Dict of system state, or None for simple call.
                If None, returns a default GoalVector (stub compatibility).

        Returns:
            GoalVector with drive_id, target_state, priority.
        """
        # Phase 3.1 compatibility: if no context, return default
        if context is None or not isinstance(context, dict):
            self._cycle += 1
            goal = GoalVector(
                drive_id=1,
                target_state=StateVector(
                    values=np.zeros(self.state_dim, dtype=np.float32),
                    precision=np.ones(self.state_dim, dtype=np.float32),
                ),
                tolerance=0.1,
                creation_cycle=self._cycle,
                priority=1.0,
            )
            self.current_goal = goal
            return goal

        # Phase 3.2: compute drives from context
        self.compute_drives(context)

        # ── Meta-stable goal locking ──
        # When meta-stable, suppress conflicting drives D1/D3/D5.
        # Only non-conflicting drives (D2, D4, D6) may generate goals.
        if self._is_deeply_meta_stable():
            # Suppress D1/D3/D5 drives (set their deficits to 0)
            for d in [1, 3, 5]:
                self.drives[d].deficit = 0.0

        # Softmax weighting of deficits (now with suppressed drives if meta-stable)
        deficits = np.array([self.drives[d].deficit for d in range(1, 6)], dtype=np.float64)
        exp_deficits = np.exp((deficits - deficits.max()) / max(self.temperature, 0.01))
        weights = exp_deficits / (exp_deficits.sum() + 1e-8)

        # Select winning drive via weighted sampling
        rng = np.random.RandomState(self._cycle)
        winner = int(rng.choice(5, p=weights)) + 1  # 1-indexed

        # Generate goal from winning drive
        goal = self._goal_from_drive(winner, weights[int(winner) - 1])

        # Push onto goal stack
        self._push_goal(goal)

        # Compute Pareto front and meta-stable state
        pareto = self.compute_pareto_front()
        self._update_meta_stable()

        self.current_goal = goal
        self._goal_history.append(goal)
        if len(self._goal_history) > 100:
            self._goal_history = self._goal_history[-50:]

        return goal

    def _goal_from_drive(
        self, drive_id: int, priority: float,
    ) -> GoalVector:
        """Generate a concrete goal from a drive's current state.

        Each drive generates a goal appropriate to its function.

        Args:
            drive_id: Drive identifier (1-6).
            priority: Softmax weight for this goal.

        Returns:
            GoalVector with drive-specific target.
        """
        drive = self.drives[drive_id]

        if drive_id == 1:
            # D1: Explore uncertain regions where confidence is low
            target = StateVector(
                values=np.ones(self.state_dim, dtype=np.float32) * 0.5,
                precision=np.ones(self.state_dim, dtype=np.float32) * 0.3,
            )
            tolerance = 0.3
        elif drive_id == 2:
            # D2: Seek criticality — adjust exploration noise
            target = StateVector(
                values=np.zeros(self.state_dim, dtype=np.float32),
                precision=np.ones(self.state_dim, dtype=np.float32) * 0.8,
            )
            tolerance = 0.15
        elif drive_id == 3:
            # D3: Practice — seek familiar states near current
            target = StateVector(
                values=np.zeros(self.state_dim, dtype=np.float32),
                precision=np.ones(self.state_dim, dtype=np.float32) * 0.9,
            )
            tolerance = 0.05  # tight — exact practice
        elif drive_id == 4:
            # D4: Explore — seek novel states
            target = StateVector(
                values=np.ones(self.state_dim, dtype=np.float32) * 0.7,
                precision=np.ones(self.state_dim, dtype=np.float32) * 0.2,
            )
            tolerance = 0.4  # loose — broad exploration
        elif drive_id == 5:
            # D5: Optimize — seek minimal action
            target = StateVector(
                values=np.zeros(self.state_dim, dtype=np.float32),
                precision=np.ones(self.state_dim, dtype=np.float32) * 1.0,
            )
            tolerance = 0.1
        else:
            # D6: Empowerment (deferred)
            target = StateVector(
                values=np.zeros(self.state_dim, dtype=np.float32),
                precision=np.ones(self.state_dim, dtype=np.float32),
            )
            tolerance = 0.5

        return GoalVector(
            drive_id=drive_id,
            target_state=target,
            tolerance=tolerance,
            creation_cycle=self._cycle,
            priority=float(priority),
        )

    # ── Goal Stack ────────────────────────────────────────────

    def _push_goal(self, goal: GoalVector) -> None:
        """Push a goal onto the goal stack with optional decomposition.

        Args:
            goal: Goal to push.
        """
        # Don't push duplicate of latest active goal
        if self.goal_stack and self.goal_stack[-1].goal.drive_id == goal.drive_id:
            return

        entry = GoalStackEntry(goal=goal, depth=0)

        # Decompose complex goals into sub-goals
        if goal.drive_id == 1:
            # D1: Explore uncertain region — decompose into approach sub-goals
            sub = GoalVector(
                drive_id=1,
                target_state=goal.target_state,
                tolerance=goal.tolerance * 2.0,
                creation_cycle=self._cycle,
                priority=goal.priority * 0.5,
            )
            entry.sub_goals = [sub]
        elif goal.drive_id == 4:
            # D4: Explore novel states — decompose into random walk steps
            for _ in range(3):
                sub = GoalVector(
                    drive_id=4,
                    target_state=goal.target_state,
                    tolerance=0.5,
                    creation_cycle=self._cycle,
                    priority=goal.priority * 0.3,
                )
                entry.sub_goals.append(sub)

        # Prune if stack is too deep
        if len(self.goal_stack) >= self._max_stack_depth:
            self.goal_stack.pop(0)  # Remove oldest

        self.goal_stack.append(entry)

    def pop_completed_goal(self) -> Optional[GoalVector]:
        """Pop the topmost completed goal from the stack.

        Returns:
            The completed GoalVector, or None if no completed goal.
        """
        while self.goal_stack:
            top = self.goal_stack[-1]
            if not top.sub_goals:
                if top.completed:
                    return self.goal_stack.pop().goal
                else:
                    return None  # Top is not completed
            # Process sub-goals first
            sub_done = all(sg.completed for sg in top.sub_goals)
            if sub_done:
                return self.goal_stack.pop().goal
            return None
        return None

    def mark_current_goal_completed(self) -> None:
        """Mark the current goal as completed."""
        if self.goal_stack:
            self.goal_stack[-1].completed = True
        if self.current_goal is not None:
            self.current_goal = None

    # ── Meta-Stable State ─────────────────────────────────────

    def _update_meta_stable(self) -> None:
        """Update meta-stable state based on Pareto front.

        Meta-stability occurs when all active drives (D1-D5) have
        deficits below threshold for min_cycles.
        """
        deficits = [self.drives[d].deficit for d in range(1, 6)]
        all_satisfied = all(d < self._meta_stable_threshold for d in deficits)

        if all_satisfied:
            if not self.meta_stable.is_meta_stable:
                # Entering meta-stable state
                self.meta_stable.is_meta_stable = True
                self.meta_stable.drive_values = list(deficits)
                self.meta_stable.cycles_since_entry = 1
            else:
                self.meta_stable.cycles_since_entry += 1
        else:
            self.meta_stable.is_meta_stable = False
            self.meta_stable.cycles_since_entry = 0

    def _is_deeply_meta_stable(self) -> bool:
        """Check if system is in a stable meta-stable state (min cycles elapsed).

        Once meta-stable, conflicting drives D1/D3/D5 are suppressed.
        Only D2 (criticality), D4 (epistemic curiosity), and D6 (empowerment)
        may generate new goals.

        Returns:
            True if meta-stable and min cycles threshold met.
        """
        return (self.meta_stable.is_meta_stable
                and self.meta_stable.cycles_since_entry >= self._meta_stable_min_cycles)

    def is_meta_stable(self) -> bool:
        """Public API: check if system is meta-stable (any state).

        Returns:
            True if all drives below threshold.
        """
        return self.meta_stable.is_meta_stable

    # ── Drive Summary ─────────────────────────────────────────

    def get_drive_summary(self) -> Dict[str, float]:
        """Get a summary of current drive deficits.

        Returns:
            Dict mapping drive name → deficit value.
        """
        return {
            f"D{d}": self.drives[d].deficit
            for d in range(1, 6)
        }

    def get_winning_drive(self) -> int:
        """Get the drive ID with the highest current deficit.

        Returns:
            Drive ID (1-5) with maximum deficit.
        """
        deficits = {d: self.drives[d].deficit for d in range(1, 6)}
        return max(deficits, key=deficits.get)  # type: ignore[arg-type]

    # ── Reset ─────────────────────────────────────────────────

    def reset(self) -> None:
        """Reset MDIM state for a new training run."""
        self._cycle = 0
        self.drives = {d: DriveState(drive_id=d) for d in range(1, 7)}
        self.goal_stack.clear()
        self.meta_stable = MetaStableState()
        self.current_goal = None
        self._drive_history.clear()
        self._goal_history.clear()
