[package]
name = "phca-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
numpy = { workspace = true }
pyo3 = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }

[lib]
crate-type = ["lib", "cdylib"]
